### ISSUE TITLE
Creswell 

### ISSUE THREAD

**Issue by PASisson** [MTStrot/Solar-Overlay#4]
**Tracker 12** has a Motor 0 showing faulted -red  - MO is an inactive icon and needs to be removed or set with an alternate reading so that it doesn't indicate there is an issue. 

**Inv 8** has false color indications for site showing as Green no issues - however 2 Inverters have faults 

**Jemstar** is in No comms?  No reading and it has a flashing box around it which in Grantek indicates comms error

**Comment by MTStrot** [comment]
-Jemstar was fixed in a previous ticket
-Motor 0 has been hidden
-I'm not sure how things looked at the time, but I'm seeing inverter 3 and inverter 8 correctly showing module faults right now.  It also looked it tripped the day you put in the ticket:
![image](https://user-images.githubusercontent.com/33523612/72090207-9529e980-32db-11ea-9031-6f843e12330c.png)

Maybe you were looking on the solar servers instead of the wind ones?
